name: Lint Python Code

on: [push, pull_request]  # se déclenche à chaque push ou PR

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint **/*.py
